version: '3'

services:

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - actividades
    ports:
      - 80:80
      
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules

  actividades:
    build:
      dockerfile: Dockerfile
      context: ./actividades
    container_name: actividades
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/users/node_modules